name: lint
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: SSH Setting
        env:
          AKARI_REPO_SSH_PRIVATE_KEY: ${{ secrets.AKARI_REPO_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p /home/runner/.ssh/
          echo -e ${AKARI_REPO_SSH_PRIVATE_KEY} | base64 -d > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: poetry

      - run: poetry install

      - uses: AustinScola/mypy-cache-github-action@v1
        name: Cache mypy cache

      - run: make lint
      - run: make test
